name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


permissions:
  contents: read

jobs:
  # Build and test
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ["8.10", "9.0", "9.2", "9.4", "9.6", "9.8", "9.10", "9.12", "9.14"]
        cabal: ["3.16"]
        os: [ubuntu-latest]

    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Haskell
      id: setup-haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        cabal-update: true

    - name: Configure the build
      run: |
        cabal configure --enable-test --enable-benchmark --ghc-options="-Werror"
        cat cabal.project.local

    - name: Record cabal dependencies

      run: |
        cabal build all --dry-run

    - name: "Restore cache"
      uses: actions/cache/restore@v4
      id: restore-cabal-cache
      env:
        cache-name: cache-cabal-build-${{ matrix.os }}-ghc-${{ steps.setup-haskell.outputs.ghc-version }}-cabal-${{ steps.setup-haskell.outputs.cabal-version }}
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ env.cache-name }}-${{ hashFiles('dist-newstyle/cache/plan.json') }}
        restore-keys: ${{ env.cache-name }}-

    - name: Install cabal dependencies
      id: build-dependencies
      run: cabal build --only-dependencies all

    - name: "Save cache"
      uses: actions/cache/save@v4
      # Note: cache-hit will be set to true only when cache hit occurs for the
      # exact key match. For a partial key match via restore-keys or a cache
      # miss, it will be set to false.
      if: steps.build-dependencies.outcome == 'success' && steps.restore-cabal-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key:  ${{ steps.restore-cabal-cache.outputs.cache-primary-key }}

    - name: Build
      run: cabal build all

    - name: Run tests
      env:
        TASTY_TIMEOUT: "5m"
      run: |
        cabal test -j1 --test-show-details=direct all

  ################################################################################
  # Lint with cabal-fmt
  ################################################################################
  lint-cabal-fmt:
    name: Lint with cabal-fmt
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v6

    - name: 🛠️ Setup cabal-fmt
      uses: jorisdral/actions/setup-cabal-fmt@cabal-fmt-v0
      with:
        cabal-fmt-version: "0.1.12"
        ghc-version: "9.6"
        cabal-version: "3.16"
        # The index-state is fixed to enable caching and ensure that the version
        # regardless of the current state of Hackage head.
        # If you want a newer version of cabal-fmt, use a more recent time.
        hackage-index-state: "2026-03-02T00:00:00Z"

    - name: 🎗️ Lint with cabal-fmt
      run: ./scripts/format-cabal-fmt.sh && git diff --exit-code

  ################################################################################
  # Lint with stylish-haskell
  ################################################################################
  lint-stylish-haskell:
    name: Lint with stylish-haskell
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v6

    - name: 🛠️ Setup stylish-haskell
      uses: jorisdral/actions/setup-stylish-haskell@stylish-haskell-v0
      with:
        stylish-haskell-version: "0.15.1.0"
        ghc-version: "9.10"
        cabal-version: "3.16"
        # The index-state is fixed to enable caching and ensure that the version
        # regardless of the current state of Hackage head.
        # If you want a newer version of stylish-haskell, use a more recent time.
        hackage-index-state: "2026-03-02T00:00:00Z"

    - name: 🎗️ Lint with stylish-haskell
      run: ./scripts/format-stylish-haskell.sh && git diff --exit-code